/****** Object:  StoredProcedure [dbo].[SP_GetAllUsers]    Script Date: 2/14/2021 10:34:27 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



CREATE   PROCEDURE [dbo].[SP_GetAllUsers]
AS
BEGIN
	SELECT [ID], [USERNAME], [FIRSTNAME], [LASTNAME], [EMAILADDRESS], [STATE], [AGE], [GENDER] FROM [DBO].[USERS]
END
GO


