/****** Object:  Table [dbo].[Users]    Script Date: 1/14/2021 1:47:36 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Users](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[UserName] [nvarchar](40) NOT NULL,
	[FirstName] [nvarchar](40) NOT NULL,
	[LastName] [nvarchar](40) NOT NULL,
	[EmailAddress] [nvarchar](100) NOT NULL,
	[State] [char](2) NULL,
	[Age] [tinyint] NOT NULL,
	[Gender] [char](1) NULL,
	[Password] [nvarchar](400) NULL,
 CONSTRAINT [PK_Users] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UQ_EMAILADDRESS] UNIQUE NONCLUSTERED 
(
	[EmailAddress] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UQ_USERNAME] UNIQUE NONCLUSTERED 
(
	[UserName] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Users]  WITH CHECK ADD  CONSTRAINT [FK_StateCode] FOREIGN KEY([State])
REFERENCES [dbo].[States] ([StateCode])
GO

ALTER TABLE [dbo].[Users] CHECK CONSTRAINT [FK_StateCode]
GO

ALTER TABLE [dbo].[Users]  WITH CHECK ADD  CONSTRAINT [CK_AGE] CHECK  (([AGE]>(0) AND [AGE]<(130)))
GO

ALTER TABLE [dbo].[Users] CHECK CONSTRAINT [CK_AGE]
GO


